dataset:
  train_set: CEC2.train.1
  test_set: CEC2.test.1

train_path:
  clarity_data_dir: /fastdata/acq22jb/DP/Data/cpc2/clarity_CPC2_data_train
  metadata_dir: ${train_path.clarity_data_dir}/clarity_data/metadata
  signal_dir: ${train_path.clarity_data_dir}/clarity_data/HA_outputs/signals/CEC2
  scene_dir: ${train_path.clarity_data_dir}/clarity_data/scenes/CEC2
  exp_dir: /fastdata/acq22jb/DP/Data/cpc2/bessemer_asr1

test_path:
  clarity_data_dir: /fastdata/acq22jb/DP/Data/cpc2/clarity_CPC2_data_test
  metadata_dir: ${test_path.clarity_data_dir}/clarity_data/metadata
  signal_dir: ${test_path.clarity_data_dir}/clarity_data/HA_outputs/signals/CEC2
  scene_dir: ${test_path.clarity_data_dir}/clarity_data/scenes/CEC2
  exp_dir: /fastdata/acq22jb/DP/Data/cpc2/bessemer_asr1

dev_percent: 0.1  # amount of signals for dev set
test_percent: 0.1  # amount of signals for test set
ref_sr: 32000  # sample rate of HA signals
target_sr: 16000  # sample rate for resampling

MSBGEar: # hyperparameters for MSBG ear
  src_pos: ff
  sample_rate: 44100
  equiv_0db_spl: 100
  ahr: 20

asr_config: transformer_cpc2.yaml  # path

defaults:
  - _self_
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

hydra:
  output_subdir: Null
  run:
    dir: .
